// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANi9pJbbosUHrf3gz7Nd0gJy6sstsXZ-g',
    appId: '1:668992767253:web:9522fa92e8c0dd6c0f151c',
    messagingSenderId: '668992767253',
    projectId: 'knack---the-learning-platform',
    authDomain: 'knack---the-learning-platform.firebaseapp.com',
    storageBucket: 'knack---the-learning-platform.appspot.com',
    measurementId: 'G-SXPD828XLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnz9E5KFOMHLJoTcIta8bEIS4YN-Q-f1s',
    appId: '1:668992767253:android:bc610a58d72484610f151c',
    messagingSenderId: '668992767253',
    projectId: 'knack---the-learning-platform',
    storageBucket: 'knack---the-learning-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhojeWO2BXMAZmE_GddX0h1Y9WDmJ-ra4',
    appId: '1:668992767253:ios:c38298c8bffc37370f151c',
    messagingSenderId: '668992767253',
    projectId: 'knack---the-learning-platform',
    storageBucket: 'knack---the-learning-platform.appspot.com',
    androidClientId: '668992767253-jugmmq1gpe94j1k9k77jmv0gdgrm6eoq.apps.googleusercontent.com',
    iosClientId: '668992767253-g39gonku5qajj6774h8trbdncl9fipn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.knack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhojeWO2BXMAZmE_GddX0h1Y9WDmJ-ra4',
    appId: '1:668992767253:ios:0bfa9c142d447b200f151c',
    messagingSenderId: '668992767253',
    projectId: 'knack---the-learning-platform',
    storageBucket: 'knack---the-learning-platform.appspot.com',
    androidClientId: '668992767253-jugmmq1gpe94j1k9k77jmv0gdgrm6eoq.apps.googleusercontent.com',
    iosClientId: '668992767253-gs69lkth4sm5co263qf6p44php7iur3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.knack.RunnerTests',
  );
}
